import Head from 'next/head'
import Image from 'next/image'
import { Hero } from '../sections'
import { Container1 } from '../components'



export default function Home() {
  return (<>
  <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
  </Head>

    <Container1>
    <Hero />
        </Container1 >
  
  </>

    


      

  )
}
